blank_issues_enabled: true
contact_links:
  - name: Ask a question on Discord
    url: https://discord.gg/CFUYP246zU
    about: For questions or discussion, chat with the team on Discord instead of opening an issue.
